#!/bin/sh
#
toilet --metal `uname -n` -f mono12 | sed 's/^.//'
printf "Welcome to %s (%s %s %s)\n" "$DISTRIB_DESCRIPTION" "$(uname -o)" "$(uname -r)" "$(uname -m)"
printf "\n"
UPTIME=`uptime | sed 's/^.//'`
printf "$UPTIME"
printf "\n"
